import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@styles/global.scss";
import { Header } from "@components/Header";
import { Footer } from "@components/Footer";
import { FacilitiesProvider, QueryProvider } from "@/components/Context";
import styles from "./page.module.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <QueryProvider>
          <FacilitiesProvider>
            <main className={styles.pageContainer}>
              <div className={styles.pageContent}>{children}</div>
            </main>
          </FacilitiesProvider>
        </QueryProvider>
        <Footer />
      </body>
    </html>
  );
}
